apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: test
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: http://127.0.0.1:5000
  - name: traceHeaders
    value: true